assetmanager/assetmanager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('stocks/', include('stock.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assetmanager/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('', views.inbox, name='inbox'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/<int:stock_pk>/', views.new_conversation, name='new'),
]

assetmanager/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

assetmanager/stock/urls.py
from django.urls import path

from . import views

app_name = 'stock'

urlpatterns = [
    path('', views.stocks, name='stocks'),
    path('ticker/<str:ticker>/', views.ticker, name='ticker'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
]

assetmanager/stock/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Asset(models.Model):
    category = models.ForeignKey(Category, related_name='assets', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    currency = models.CharField(max_length=255)
    quantity = models.FloatField()
    created_by = models.ForeignKey(User, related_name='assets', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class Stock(Asset):
    ticker = models.CharField(max_length=255)
    purchase_price = models.FloatField()
    purchased_at = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.name

# class Cash(Asset):
#
#     def __str__(self):
#         return self.name

assetmanager/stock/forms.py
from django import forms

from .models import Stock

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class NewStockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ('category', 'name', 'ticker', 'quantity', 'purchase_price', 'currency', 'purchased_at')
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'ticker': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'quantity': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'purchase_price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'currency': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'purchased_at': forms.DateTimeInput(attrs={
                "type": "date"
            }),
        }


class EditStockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ('name', 'ticker', 'quantity', 'purchase_price', 'currency', 'purchased_at')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'ticker': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'quantity': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'purchase_price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'currency': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'purchased_at': forms.DateTimeInput(attrs={
                "type": "date"
            }),

        }

assetmanager/stock/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .forms import NewStockForm, EditStockForm
from .models import Category, Stock


def stocks(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    categories = Category.objects.all()
    stocks = Stock.objects.all()

    if category_id:
        stocks = stocks.filter(category_id=category_id)

    if query:
        stocks = stocks.filter(Q(name__icontains=query) | Q(ticker__icontains=query))

    return render(request, 'stock/stocks.html', {
        'stocks': stocks,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })


def ticker(request, ticker):
    stocks = Stock.objects.filter(Q(created_by=request.user) & Q(ticker=ticker))

    return render(request, 'stock/ticker.html', {
        'stocks': stocks,
    })


def detail(request, pk):
    stock = get_object_or_404(Stock, pk=pk)
    return render(request, 'stock/detail.html', {
        'stock': stock,
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewStockForm(request.POST, request.FILES)

        if form.is_valid():
            stock = form.save(commit=False)
            stock.created_by = request.user
            stock.save()

            return redirect('stock:detail', pk=stock.id)
    else:
        form = NewStockForm()

    return render(request, 'stock/form.html', {
        'form': form,
        'title': 'New stock',
    })


@login_required
def edit(request, pk):
    stock = get_object_or_404(Stock, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditStockForm(request.POST, request.FILES, instance=stock)

        if form.is_valid():
            form.save()

            return redirect('stock:detail', pk=stock.id)
    else:
        form = EditStockForm(instance=stock)

    return render(request, 'stock/form.html', {
        'form': form,
        'title': 'Edit stock',
    })


@login_required
def delete(request, pk):
    stock = get_object_or_404(Stock, pk=pk, created_by=request.user)
    stock.delete()

    return redirect('dashboard:index')

assetmanager/stock/templates/stock/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ stock.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ stock.name }}</h1>
        <p class="text-gray-500"><strong>Quantity: </strong>{{ stock.quantity }}</p>
        <p class="text-gray-500"><strong>Purchase date: </strong>{{ stock.purchased_at }}</p>

        {% if request.user == stock.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your stock!</p>

                <a href="{% url 'stock:edit' stock.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'stock:delete' stock.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            </div>
        {% else %}  
            <a href="{% url 'conversation:new' stock.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact seller</a>
        {% endif %}
    </div>
</div>

{% endblock %}

assetmanager/stock/templates/stock/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

assetmanager/stock/templates/stock/stocks.html
{% extends 'core/base.html' %}

{% block title %}Stocks{% endblock %}

{% block content %}
    <div class="pb-6 grid grid-cols-4 gap-4 bg-gray-100">
        <div class="col-span-1">
            <form method="get" action="{% url 'stock:stocks' %}">
                <input name="query" class="w-full py-4 px-6 border rounded-xl" type="text" value="{{ query }}" placeholder="Find a bike, a chair or car...">

                <button class="mt-2 py-4 px-8 text-lg bg-teal-500 text-white rounded-xl">Search</button>
            </form>

            <hr class="my-6">

            <p class="font-semibold">Categories</p>

            <ul>
                {% for category in categories %}
                    <li class="py-2 px-2 rounded-xl{% if category.id == category_id %} bg-gray-200{% endif %}">
                        <a href="{% url 'stock:stocks' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                    </li>
                {% endfor %}
            </ul>

            <hr class="my-6">

            <p class="font-semibold">Clear filters</p>

            <ul>
                <li><a href="{% url 'stock:stocks' %}" class="mt-2 py-4 px-8 inline-block bg-yellow-500 text-lg rounded-xl text-white">Clear</a>
                </li>
            </ul>
        </div>

        <div class="col-span-3">
            <div class="grid grid-cols-3 gap-3">
                {% for stock in stocks %}
                    <div>
                        <a href="{% url 'stock:detail' stock.id %}">
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ stock.name }}</h2>
                                <p class="text-gray-500">Quantity: {{ stock.quantity }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

assetmanager/stock/templates/stock/ticker.html
{% extends 'core/base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">My stocks</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for stock in stocks %}
                <div>
                    <a href="{% url 'stock:detail' stock.id %}">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ stock.name }}</h2>
                            <p class="text-gray-500">Quantity: {{ stock.quantity }}</p>
                            <p class="text-gray-500">Purchase price: {{ stock.purchase_price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}